### ISSUE TITLE
Not Working on my Kali machine

### ISSUE THREAD

**Issue by TheJostler** [m8r0wn/subscraper#10]
Hello I downloaded and installed the sub scraper and tried to run it on my Kali computer
**Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2021.2
Codename:       kali-rolling**

however when I try to run the program for any domain it returns:

**_[Source]             Subdomain                               
[Error-01]      No module named 'censys.certificates'

[*] Identified None subdomain(s) in 0:00:00.354822
[*] Subdomains written to ./subscraper_report.txt_**  

and the .txt file is empty.
I'm not sure why it's not working on my machine

**Comment by m8r0wn** [comment]
Hi @TheJostler,

Try ```git pull``` that should resolve the issue

Thanks,
\-m8r0wn
