### ISSUE TITLE
please use one of existing tools

### ISSUE THREAD

**Issue by blshkv** [m8r0wn/subscraper#3]
There are like 10 various  subdomain enumerators. Please port your ideas into one of them.
The incomplete list is here:
https://github.com/pentoo/pentoo-overlay/issues/273

**Comment by m8r0wn** [comment]
Hi @blshkv,

Thanks for the input, I agree there are a number of great subdomain enumeration tools out there already. I created SubScraper a while ago to get the data I wanted, in the format I wanted. It was just recently I made the decision to release it opensource. Sharing ideas/contributing always benefits the community and I will look into making contributions to other subdomain enumeration tools as well!

-m8r0wn

**Comment by blshkv** [comment]
Ok, noted. Im trying to unite all these tools into one but the best one. Living in the perfect world :)

**Comment by kingsalman99** [comment]
> Hi @blshkv,
> 
> Thanks for the input, I agree there are a number of great subdomain enumeration tools out there already. I created SubScraper a while ago to get the data I wanted, in the format I wanted. It was just recently I made the decision to release it opensource. Sharing ideas/contributing always benefits the community and I will look into making contributions to other projects as well!
> 
> -m8r0wn

bro Can I install it on Termux ??

**Comment by m8r0wn** [comment]
Not being 100% familiar with Termux I cant say definitely. However, if you can install python3  and the dependencies in [requirements.txt](https://github.com/m8r0wn/subscraper/blob/master/requirements.txt) I dont see why not. Another option is to setup a remote system and use Termux to SSH over and execute SubScraper from there.

Hope this helped!
-m8r0wn

**Comment by kingsalman99** [comment]
Okay ,bro Thanks ,for Your reply

Pada tanggal Sen, 8 Jun 2020 7.35 PM, Mike <notifications@github.com>
menulis:
