### ISSUE TITLE
Input file not found, even though It's there

### ISSUE THREAD

**Issue by Cloufish** [m8r0wn/subscraper#6]
Simple problem. I want to search javascript files from URLs that are in the file javascript_files.txt, but the script complains about input file not found
![image](https://user-images.githubusercontent.com/32965886/97777884-6420eb00-1b73-11eb-9dd4-70e2d6a3985c.png)

**Comment by m8r0wn** [comment]
What data is in the "javascript_files.txt" file? Additionally, if you don't mind, what is the full command here (feel free to obfuscate/modify). Are you providing a target input?

It almost sounds like the wrong project. This version of subscraper is **100% passive** and does not spider the site to find subdomains in JavaScript files. Were you thing of this ![subscraper](https://github.com/Cillian-Collins/subscraper), or there is also a Taser example script ![jsearch.py](https://github.com/m8r0wn/taser/tree/master/examples) capable of identifying subdomains from input files like you are suggesting?

**Comment by m8r0wn** [comment]
Closing, not enough details. Feel free to reopen if this has not solved your issue.
